### ISSUE TITLE
cant find spotify connect devices

### ISSUE THREAD

**Issue by maddin78** [amueller-tech/spotifycontroller#1]
hi

i cant find spotify connect devices when i search http://localhost:5005/getDevices. when i open the web app from spotify and connect with the same account i use with the pi i can find it, i have installed raspotify to the sonos kids controller pi and can play musik on it with my iphone and pc. but not with spotifycontroller

**Comment by maddin78** [comment]
now it works, i have added the spotify login data into the raspotify config. this changes the id. i added the new one to the sonos config.json and it worked. i have now a standalone box

**Comment by amueller-tech** [comment]
Hi,

glad it works now.

I just tried it myself and noticed the following:
- after installing raspotify (in a docker container), only my phone found the device, the spotify web player as well as 
  spotifycontroller coudn't find it.
- after playing to it once on the phone, the web app and also http://localhost:5005/getDevices found the device.
