### ISSUE TITLE
Spotify connect controller not working on loopback device

### ISSUE THREAD

**Issue by HeikoGr** [amueller-tech/spotifycontroller#2]
I'm building an all-in-one Device with raspotify as spotify connect target.

I had to configure the Sonos-Kids-Controller with the external wifi ip-address. The Loopback device won't work.

**Comment by amueller-tech** [comment]
Does the loopback device return the devices, e.g. if you open http://localhost:5005/getDevices in a webbrowser?
I cannot reproduce it, localhost works perfectly fine over here.

**Comment by HeikoGr** [comment]
Sorry. I missed to answer. Can't reproduce it either anymore...

**Comment by amueller-tech** [comment]
np, so it's working now?

**Comment by HeikoGr** [comment]
Yes, its working like a charm now. i changed so many things and reinstalled every piece of software. i don't know what the origin of my problem was...

**Comment by amueller-tech** [comment]
as always :-) Glad it works now, have fun with it!
