### ISSUE TITLE
getdevices

### ISSUE THREAD

**Issue by tlrider99** [amueller-tech/spotifycontroller#3]
Hi ,

I get only 1 spotify_connect device on localhost:5005/getDevices.

[{"id":"f3f925bfa847xxxxxx5eac119d9f267581ca66d","is_active":true,"is_private_session":false,"is_restricted":false,"name":"HOME2","type":"Computer","volume_percent":35}].

The device that is found is the PC.
What can I do to see all devices? I use Yamaha Musiccast speakers.

Thanks in advance

**Comment by amueller-tech** [comment]
Hi,

for some devices the used library [spotify-web-api-node](https://github.com/thelinmichael/spotify-web-api-node) cannot find them the first time they appear as they don't behave like real spotify connect devices, there's more info [here](https://github.com/spotify/web-api/issues/787):


Try to play to the device via the spotify app and run the discovery again.
This works for my google audio chromecast.

**Comment by tlrider99** [comment]
Hi,
this is what I thought and tried. Although tracks from spotify were played on 2 speakers, the devices are not found. Do you have another idea?
Thanks!
