### ISSUE TITLE
Spotify-Connect Button missed

### ISSUE THREAD

**Issue by tlrider99** [amueller-tech/spotifycontroller#5]
Hi ,

I miss the Spotify Connect selection button you included in your version of the Sonos Kids controller. I have installed everything as described on your page. Do you have any idea?
Thanks.

**Comment by amueller-tech** [comment]
Note: This is not related to the spotifycontroller.

Did you install this fork:
https://github.com/amueller-tech/Sonos-Kids-Controller

make sure you enable spotify-connect in the config file (set enabled to true).
Only then the div in the html is shown.

    "spotify-connect": {
        "enabled": "true",
        "server": "127.0.0.1",
        "port": "5005"
    }

Note: I stopped developing it as I'm only using one spotify device that is hard coded in the config. This allows me to always use Thyraz latest version.
